                                                                                                                                                                                                                                                                                                                                            <?php
                                                                                                                                                                                                                                                                                                                                            include('partners_header.php');
                                                                                                                                                                                                                                                                                                                                            $errors=array();
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            ?>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            <nav class="py-2">
                                                                                                                                                                                                                                                                                                                                            <ol class="breadcrumb">
                                                                                                                                                                                                                                                                                                                                            <li class="breadcrumb-item">
                                                                                                                                                                                                                                                                                                                                            <a href="index.php">Home</a>
                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            <li class="breadcrumb-item active">withdraw
                                                                                                                                                                                                                                                                                                                                            </li>				
                                                                                                                                                                                                                                                                                                                                            </ol>
                                                                                                                                                                                                                                                                                                                                            </nav>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            <div class="auth-content">
                                                                                                                                                                                                                                                                                                                                            <div class="card">
                                                                                                                                                                                                                                                                                                                                            <div class="card-body text-center">
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            <h6 class="mb-4 text-muted">minimum withdraw is 150</br> 6% withdrawal fee</h6>
                                                                                                                                                                                                                                                                                                                                            <form autocomplete="off" action="withdraw.php"  method="POST" enctype="multipart/form-data" name="categoryform">
                                                                                                                                                                                                                                                                                                                                            <?php include('errors.php');
                                                                                                                                                                                                                                                                                                                                            if (isset($_SESSION['success'])) : ?>
                                                                                                                                                                                                                                                                                                                                            <div class="error success" >
                                                                                                                                                                                                                                                                                                                                            <h6>
                                                                                                                                                                                                                                                                                                                                            <?php 
                                                                                                                                                                                                                                                                                                                                            echo $_SESSION['success']; 
                                                                                                                                                                                                                                                                                                                                            unset($_SESSION['success']);
                                                                                                                                                                                                                                                                                                                                            ?>
                                                                                                                                                                                                                                                                                                                                            </h6>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                            <?php endif ?>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            <div class="form-group text-left">
                                                                                                                                                                                                                                                                                                                                            <label for="email">mpesa phone number</label>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            <input class="form-control" type='tel' placeholder="07****" name="phone" id="exampleInputPassword1" value="<?php $tel= mysqli_query($conn,"SELECT * from users WHERE username='$username'");
                                                                                                                                                                                                                                                                                                                                            while($row = mysqli_fetch_assoc($tel)) { $phone = $row['tel']; 
                                                                                                                                                                                                                                                                                                                                            $phone= (string)((int)($phone));
                                                                                                                                                                                                                                                                                                                                            if($country == 'kenya'){
                                                                                                                                                                                                                                                                                                                                            $phone="254".$phone;
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            elseif($country=='uganda'){
                                                                                                                                                                                                                                                                                                                                            $phone ="256".$phone;
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            elseif($country =="tanzania"){
                                                                                                                                                                                                                                                                                                                                            $phone ="255".$phone;
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            elseif($country == "rwanda"){
                                                                                                                                                                                                                                                                                                                                            $phone = "250".$phone;
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            echo $phone; ?>" required="required">
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            <div class="form-group text-left">
                                                                                                                                                                                                                                                                                                                                            <label for="email">Amount</label>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            <input class="form-control" type="tel" placeholder="amount" name="amount" id="amount" value="<?php 
                                                                                                                                                                                                                                                                                                                                            $tot = 0;
                                                                                                                                                                                                                                                                                                                                            $tot = $row['bal'];} echo $tot;?>"required="required">
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            <div class="form-group text-left">
                                                                                                                                                                                                                                                                                                                                            <label for="password">username</label>
                                                                                                                                                                                                                                                                                                                                            <input type="text" class="form-control" disabled value="<?php echo $username;?>">
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            <div class="form-group text-left">
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            <input type="submit" class="btn btn-primary shadow-2 mb-4" name="submit" value="withdraw">
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            <?php
                                                                                                                                                                                                                                                                                                                                            if(isset($_POST['submit'])){
                                                                                                                                                                                                                                                                                                                                            function test_input($data) {
                                                                                                                                                                                                                                                                                                                                            $data = trim($data);
                                                                                                                                                                                                                                                                                                                                            $data = stripslashes($data);
                                                                                                                                                                                                                                                                                                                                            $data = htmlspecialchars($data);
                                                                                                                                                                                                                                                                                                                                            return $data;
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            $username = $username;
                                                                                                                                                                                                                                                                                                                                            $phone= test_input($_POST["phone"]);
                                                                                                                                                                                                                                                                                                                                            $amount = test_input($_POST["amount"]);
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            $amount = (int)$amount;
                                                                                                                                                                                                                                                                                                                                            $amount=(int)$amount;
                                                                                                                                                                                                                                                                                                                                            $ded = $amount*7;
                                                                                                                                                                                                                                                                                                                                            $ded = $ded/100;
                                                                                                                                                                                                                                                                                                                                            $Amount = $amount-$ded;
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            //  echo $amount;
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            if($tot<150){
                                                                                                                                                                                                                                                                                                                                            array_push($errors,"minimum withdrawal is kes 150");
                                                                                                                                                                                                                                                                                                                                            echo "<script> alert('minimum withdrawal is kes 150')</script>";
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            if($amount>$tot){
                                                                                                                                                                                                                                                                                                                                            array_push($errors,"you have insufficient funds in your account");
                                                                                                                                                                                                                                                                                                                                            echo "<script> alert('you have insufficient funds in your account')</script>";
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            if(count($errors)==0){
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            /* Urls */
                                                                                                                                                                                                                                                                                                                                            $access_token_url = 'https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials';
                                                                                                                                                                                                                                                                                                                                            $b2c_url = 'https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest';
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            /* Required Variables */
                                                                                                                                                                                                                                                                                                                                            $consumerKey = 'GGHr9yYvkwnQY0AtMl5kay0w7LEzGLhu';        # Fill with your app Consumer Key
                                                                                                                                                                                                                                                                                                                                            $consumerSecret = 'T72wcZHAYzZLhdGE';     # Fill with your app Secret
                                                                                                                                                                                                                                                                                                                                            $headers = ['Content-Type:application/json; charset=utf8'];
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            /* from the test credentials provided on you developers account */
                                                                                                                                                                                                                                                                                                                                            $InitiatorName = 'fidelity investments co';      # Initiator
                                                                                                                                                                                                                                                                                                                                            $SecurityCredential = 'UVzdiL7xrAeE2D2U0O2z8rNwkRVTFAYINAX2Eq/+Ra5T7Xoddtx2x1M+S+zf4rnt/L2vHYlEd8SOPSVWCZZLXkO9zXRUw6pA/Y9GJrnOfIYM3bj/hMYjdSQy3BZx9iomu04nyLpVz57Aiyp/eZKnye8iS6Tkdxj7Cj/RSDIUBSAX65zedbAeEPXQ9gw4pi3s33fcRqO1V97k506iVBE57Xv9toz/9/xGytWWJeUpnxHJukR8sDGdNfxDzkC7EnUuBl0Bhuh3MS5HGBIbsBbAuKRN9TA7fQq/UC45/mdRfUGIRVmTllCLFl5FgCvTi1yRA3aAGFjmo4LtoXVoRwwwcA=='; 
                                                                                                                                                                                                                                                                                                                                            $CommandID = 'BusinessPayment';          # choose between SalaryPayment, BusinessPayment, PromotionPayment 
                                                                                                                                                                                                                                                                                                                                            $Amount = $Amount;
                                                                                                                                                                                                                                                                                                                                            $PartyA = '174379';             # shortcode 1
                                                                                                                                                                                                                                                                                                                                            $PartyB = $phone;             # Phone number you're sending money to
                                                                                                                                                                                                                                                                                                                                            $Remarks = 'Salary';      # Remarks ** can not be empty
                                                                                                                                                                                                                                                                                                                                            $QueueTimeOutURL = 'http://www.jijaze.epizy.com/pesa/timeout.php';    # your QueueTimeOutURL
                                                                                                                                                                                                                                                                                                                                            $ResultURL = 'http://www.jijaze.epizy.com/pesa/mpesa.class.php/results';          # your ResultURL
                                                                                                                                                                                                                                                                                                                                            $Occasion = 'chrismas';           # Occasion
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            /* Obtain Access Token */
                                                                                                                                                                                                                                                                                                                                            $curl = curl_init($access_token_url);
                                                                                                                                                                                                                                                                                                                                            curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
                                                                                                                                                                                                                                                                                                                                            curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
                                                                                                                                                                                                                                                                                                                                            curl_setopt($curl, CURLOPT_HEADER, FALSE);
                                                                                                                                                                                                                                                                                                                                            curl_setopt($curl, CURLOPT_USERPWD, $consumerKey.':'.$consumerSecret);
                                                                                                                                                                                                                                                                                                                                            $result = curl_exec($curl);
                                                                                                                                                                                                                                                                                                                                            $status = curl_getinfo($curl, CURLINFO_HTTP_CODE);
                                                                                                                                                                                                                                                                                                                                            $result = json_decode($result);
                                                                                                                                                                                                                                                                                                                                            $access_token = $result->access_token;
                                                                                                                                                                                                                                                                                                                                            curl_close($curl);
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            /* Main B2C Request to the API */
                                                                                                                                                                                                                                                                                                                                            $b2cHeader = ['Content-Type:application/json','Authorization:Bearer '.$access_token];
                                                                                                                                                                                                                                                                                                                                            $curl = curl_init();
                                                                                                                                                                                                                                                                                                                                            curl_setopt($curl, CURLOPT_URL, $b2c_url);
                                                                                                                                                                                                                                                                                                                                            curl_setopt($curl, CURLOPT_HTTPHEADER, $b2cHeader); //setting custom header
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            $curl_post_data = array(
                                                                                                                                                                                                                                                                                                                                            //Fill in the request parameters with valid values
                                                                                                                                                                                                                                                                                                                                            'InitiatorName' => $InitiatorName,
                                                                                                                                                                                                                                                                                                                                            'SecurityCredential' => $SecurityCredential,
                                                                                                                                                                                                                                                                                                                                            'CommandID' => $CommandID,
                                                                                                                                                                                                                                                                                                                                            'Amount' => $Amount,
                                                                                                                                                                                                                                                                                                                                            'PartyA' => $PartyA,
                                                                                                                                                                                                                                                                                                                                            'PartyB' => $PartyB,
                                                                                                                                                                                                                                                                                                                                            'Remarks' => $Remarks,
                                                                                                                                                                                                                                                                                                                                            'QueueTimeOutURL' => $QueueTimeOutURL,
                                                                                                                                                                                                                                                                                                                                            'ResultURL' => $ResultURL,
                                                                                                                                                                                                                                                                                                                                            'Occasion' => $Occasion
                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            $data_string = json_encode($curl_post_data);
                                                                                                                                                                                                                                                                                                                                            curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
                                                                                                                                                                                                                                                                                                                                            curl_setopt($curl, CURLOPT_POST, true);
                                                                                                                                                                                                                                                                                                                                            curl_setopt($curl, CURLOPT_POSTFIELDS, $data_string);
                                                                                                                                                                                                                                                                                                                                            $curl_response = curl_exec($curl);
                                                                                                                                                                                                                                                                                                                                            //print_r($curl_response);
                                                                                                                                                                                                                                                                                                                                            // echo $curl_response;
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            $response_code = json_decode($curl_response)->ResponseCode;
                                                                                                                                                                                                                                                                                                                                            echo $response_code;
                                                                                                                                                                                                                                                                                                                                            if ($response_code==0) {
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            $_SESSION['success'] =  "Transaction is successful please wait for mpesa confirmation";
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            $sqle = "INSERT INTO withdrawn (username,phone,amount)
                                                                                                                                                                                                                                                                                                                                            VALUES ('$username','$phone' , '$amount')"; 
                                                                                                                                                                                                                                                                                                                                            mysqli_query($conn,$sqle);
                                                                                                                                                                                                                                                                                                                                            $new_bal = 0;
                                                                                                                                                                                                                                                                                                                                            $new_bal = $tot - $amount;
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            $res = "UPDATE users SET bal = '$new_bal' WHERE username='$username'";
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            if(mysqli_query($conn, $res)) {
                                                                                                                                                                                                                                                                                                                                            $title = 'congratulations';
                                                                                                                                                                                                                                                                                                                                            $msg = 'congrats your withdrawal of '."".$amount.' has been received and is being processed';
                                                                                                                                                                                                                                                                                                                                            $date = date("Y/m/d");
                                                                                                                                                                                                                                                                                                                                            $com = "INSERT INTO notifications (title,msg,username,date) VALUES('$title','$msg','$username','$date')";
                                                                                                                                                                                                                                                                                                                                            mysqli_query($conn, $com);
                                                                                                                                                                                                                                                                                                                                            echo "<script> alert('transaction success wait for Mpesa confirmation')</script>";
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            else{
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            $response_mess = json_decode($curl_response)->errorMessage;
                                                                                                                                                                                                                                                                                                                                            echo $response_mess;
                                                                                                                                                                                                                                                                                                                                            $_SESSION['msg']=$response_mess;
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            else {
                                                                                                                                                                                                                                                                                                                                            echo "<script> alert('transaction failed please retry again later')</script>";
                                                                                                                                                                                                                                                                                                                                            } 
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            ?>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            </body>
                                                                                                                                                                                                                                                                                                                                            </html>
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            